version: "3.7"
services:
  # DATABASE
  postgres:
    image: postgres:13.1
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:4210:5432"
    env_file: ./env/.env.postgres

  app:
    build:
      context: .
      dockerfile: ./dockerfile.develop
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    stdin_open: true

volumes:
  database:
    name: database
